spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    liquibaseSchema: system
    defaultSchema: public
  shell:
    interactive:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
